server:
  port: 8080
  servlet:
    context-path: /exam
    jsp:
      init-parameters:
        development: development

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 2015.com
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
                    
file: 
  upload:
    dir: d:/bak/file
  log:
    dir: d:/bak/log/exam/
    name: exam.log
      
sys:
  ver: 1.1.5

res:
  pub: login/toIn,login/doIn,login/toHome,login/doOut,login/toPwdUpdate,login/doPwdUpdate,home/toIn,home/doIn,home/toHome,home/doOut,home/sysTime
    