server:
  port: 1080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: false
file: 
  upload:
    dir: c:/bak/file
