server:
  port: 8000
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: development

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    static-locations: file:./h5
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root

hibernate:
  naming:
    physical-strategy: com.wcpdoc.core.hibernate.UpperCaseStrategy
    
runtime:
  timeout: 1000
  exUrl: 
  monitor: true
  
logging:
  config: config/log4j2.xml
      
token:
    expireMinute: 1440
    refreshMinute: 60
    
sys:
  ver: 3.6.1
